apiVersion: batch/v1
kind: Job
metadata:
  name: weaver-job-ik-hbb-inference
  labels:
    app: hwwtagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger/weaver
        command:
        - "/bin/bash"
        - "-c"
        - >
          git clone https://github.com/cmantill/weaver && cd weaver && 
          (python train.py --predict 
          --data-test '/hwwtaggervol/training/ak15_Jul27/test/QCD*/*.root' '/hwwtaggervol/training/ak15_Jul27/test/BulkGravitonToHHTo4Q*/*.root'
          --data-config data/ak15_points_pf_sv_mass_regression_Hbb.yaml
          --network-config networks/particle_net_pf_sv_mass_regression.py
          --model-prefix /hwwtaggervol/models/v04_regression/4_ak15Jul27_v04_Hbb_bsize128_fstep0p02_lr3em3_epoch-18_state.pt
          --gpus 0,1,2 --batch-size 128 
          --predict-output /hwwtaggervol/output/4_v04_ak15_regression_Hbb_Aug5_ep18.root 
          --regression-mode &
          wait)
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        resources:
          limits:
            memory: 256Gi
            cpu: "4"
            nvidia.com/gpu: "3"
          requests:
            memory: 50Gi
            cpu: "3"
            nvidia.com/gpu: "3"
      volumes:
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
              - key: gpu-type
                operator: In
                values:
                - "1080"
                - 1080Ti
                - 2080Ti
      restartPolicy: Never
  backoffLimit: 0

