apiVersion: v1
kind: Pod
metadata:
  name: graphganpodi
  labels:
    app: graphgani
spec:
  containers:
  - name: container
    image: gitlab-registry.nautilus.optiputer.net/raghsthebest/mnist-graph-gan:latest
    command: ["/bin/bash", "-c", "git clone http://github.com/raghsthebest/mnist_graph_gan && git config --global user.name 'Raghav' && git config --global user.email 'raghavk1997@yahoo.co.in' && sleep infinity"]
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      #  nvidia.com/gpu: "1"
        ephemeral-storage: 512Gi
    volumeMounts:
    - mountPath: /graphganvol
      name: graphganvol
  restartPolicy: Never
  volumes:
    - name: graphganvol
      persistentVolumeClaim:
        claimName: graphganvol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west
