apiVersion: v1
kind: Pod
metadata:
  name: hwwtaggerpod-ik
  labels:
    app: hwwtagger
spec:
  containers:
  - name: container
    image: gitlab-registry.nautilus.optiputer.net/raghsthebest/hww-tagger/weaver:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
          limits:
            memory: 12Gi
            cpu: "2"
            #nvidia.com/gpu: "3"
          requests:
            memory: 10Gi
            cpu: "1"
            #nvidia.com/gpu: "3"
    #resources:
    #  requests:
    #    memory: 4Gi
    #    cpu: "1"
      #  nvidia.com/gpu: "1"
    #    ephemeral-storage: 512Gi
    volumeMounts:
    - mountPath: /hwwtaggervol
      name: hwwtaggervol
  restartPolicy: Never
  volumes:
    - name: hwwtaggervol
      persistentVolumeClaim:
        claimName: hwwtaggervol

