apiVersion: batch/v1
kind: Job
metadata:
  name: regression-plot-hbb-ik
  labels:
    app: hwwtagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger/weaver
        command:
        - "/bin/bash"
        - "-c"
        - >
          git clone https://github.com/ikaul00/weaver && cd weaver && 
          (python3 plot_regression_fromoutput_Hbb.py 
          --ifile /hwwtaggervol/output/4_v04_ak15_regression_Hbb_Aug5_ep18.root
          --odir /hwwtaggervol/regression/test_v04_Aug15_Hbb/  &
          wait)
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        resources:
          limits:
            memory: 256Gi
            cpu: "4"
            # nvidia.com/gpu: "3"
          requests:
            memory: 50Gi
            cpu: "3"
            # nvidia.com/gpu: "3"
      volumes:
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
              - key: gpu-type
                operator: In
                values:
                - "1080"
                - 1080Ti
                - 2080Ti
      restartPolicy: Never
  backoffLimit: 0

